export const countryCodes = [
    { name: 'ANDORRA', code: 'AD' },
    { name: 'UNITED ARAB EMIRATES', code: 'AE' },
    { name: 'AFGHANISTAN', code: 'AF' },
    { name: 'ANTIGUA AND BARBUDA', code: 'AG' },
    { name: 'ANGUILLA', code: 'AI' },
    { name: 'ALBANIA', code: 'AL' },
    { name: 'ARMENIA', code: 'AM' },
    { name: 'NETHERLANDS ANTILLES', code: 'AN' },
    { name: 'ANGOLA', code: 'AO' },
    { name: 'ANTARCTICA', code: 'AQ' },
    { name: 'ARGENTINA', code: 'AR' },
    { name: 'AMERICAN SAMOA', code: 'AS' },
    { name: 'AUSTRIA', code: 'AT' },
    { name: 'AUSTRALIA', code: 'AU' },
    { name: 'ARUBA', code: 'AW' },
    { name: 'AZERBAIJAN', code: 'AZ' },
    { name: 'BOSNIA AND HERZEGOVINA', code: 'BA' },
    { name: 'BARBADOS', code: 'BB' },
    { name: 'BANGLADESH', code: 'BD' },
    { name: 'BELGIUM', code: 'BE' },
    { name: 'BURKINA FASO', code: 'BF' },
    { name: 'BULGARIA', code: 'BG' },
    { name: 'BAHRAIN', code: 'BH' },
    { name: 'BURUNDI', code: 'BI' },
    { name: 'BENIN', code: 'BJ' },
    { name: 'SAINT BARTHELEMY', code: 'BL' },
    { name: 'BERMUDA', code: 'BM' },
    { name: 'BRUNEI DARUSSALAM', code: 'BN' },
    { name: 'BOLIVIA', code: 'BO' },
    { name: 'BRAZIL', code: 'BR' },
    { name: 'BAHAMAS', code: 'BS' },
    { name: 'BHUTAN', code: 'BT' },
    { name: 'BOTSWANA', code: 'BW' },
    { name: 'BELARUS', code: 'BY' },
    { name: 'BELIZE', code: 'BZ' },
    { name: 'CANADA', code: 'CA' },
    { name: 'COCOS (KEELING) ISLANDS', code: 'CC' },
    { name: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', code: 'CD' },
    { name: 'CENTRAL AFRICAN REPUBLIC', code: 'CF' },
    { name: 'CONGO', code: 'CG' },
    { name: 'SWITZERLAND', code: 'CH' },
    { name: 'COTE D IVOIRE', code: 'CI' },
    { name: 'COOK ISLANDS', code: 'CK' },
    { name: 'CHILE', code: 'CL' },
    { name: 'CAMEROON', code: 'CM' },
    { name: 'CHINA', code: 'CN' },
    { name: 'COLOMBIA', code: 'CO' },
    { name: 'COSTA RICA', code: 'CR' },
    { name: 'CUBA', code: 'CU' },
    { name: 'CAPE VERDE', code: 'CV' },
    { name: 'CHRISTMAS ISLAND', code: 'CX' },
    { name: 'CYPRUS', code: 'CY' },
    { name: 'CZECH REPUBLIC', code: 'CZ' },
    { name: 'GERMANY', code: 'DE' },
    { name: 'DJIBOUTI', code: 'DJ' },
    { name: 'DENMARK', code: 'DK' },
    { name: 'DOMINICA', code: 'DM' },
    { name: 'DOMINICAN REPUBLIC', code: 'DO' },
    { name: 'ALGERIA', code: 'DZ' },
    { name: 'ECUADOR', code: 'EC' },
    { name: 'ESTONIA', code: 'EE' },
    { name: 'EGYPT', code: 'EG' },
    { name: 'ERITREA', code: 'ER' },
    { name: 'SPAIN', code: 'ES' },
    { name: 'ETHIOPIA', code: 'ET' },
    { name: 'FINLAND', code: 'FI' },
    { name: 'FIJI', code: 'FJ' },
    { name: 'FALKLAND ISLANDS (MALVINAS)', code: 'FK' },
    { name: 'MICRONESIA, FEDERATED STATES OF', code: 'FM' },
    { name: 'FAROE ISLANDS', code: 'FO' },
    { name: 'FRANCE', code: 'FR' },
    { name: 'GABON', code: 'GA' },
    { name: 'UNITED KINGDOM', code: 'GB' },
    { name: 'GRENADA', code: 'GD' },
    { name: 'GEORGIA', code: 'GE' },
    { name: 'GHANA', code: 'GH' },
    { name: 'GIBRALTAR', code: 'GI' },
    { name: 'GREENLAND', code: 'GL' },
    { name: 'GAMBIA', code: 'GM' },
    { name: 'GUINEA', code: 'GN' },
    { name: 'EQUATORIAL GUINEA', code: 'GQ' },
    { name: 'GREECE', code: 'GR' },
    { name: 'GUATEMALA', code: 'GT' },
    { name: 'GUAM', code: 'GU' },
    { name: 'GUINEA-BISSAU', code: 'GW' },
    { name: 'GUYANA', code: 'GY' },
    { name: 'HONG KONG', code: 'HK' },
    { name: 'HONDURAS', code: 'HN' },
    { name: 'CROATIA', code: 'HR' },
    { name: 'HAITI', code: 'HT' },
    { name: 'HUNGARY', code: 'HU' },
    { name: 'INDONESIA', code: 'ID' },
    { name: 'IRELAND', code: 'IE' },
    { name: 'ISRAEL', code: 'IL' },
    { name: 'ISLE OF MAN', code: 'IM' },
    { name: 'INDIA', code: 'IN' },
    { name: 'IRAQ', code: 'IQ' },
    { name: 'IRAN, ISLAMIC REPUBLIC OF', code: 'IR' },
    { name: 'ICELAND', code: 'IS' },
    { name: 'ITALY', code: 'IT' },
    { name: 'JAMAICA', code: 'JM' },
    { name: 'JORDAN', code: 'JO' },
    { name: 'JAPAN', code: 'JP' },
    { name: 'KENYA', code: 'KE' },
    { name: 'KYRGYZSTAN', code: 'KG' },
    { name: 'CAMBODIA', code: 'KH' },
    { name: 'KIRIBATI', code: 'KI' },
    { name: 'COMOROS', code: 'KM' },
    { name: 'SAINT KITTS AND NEVIS', code: 'KN' },
    { name: 'KOREA DEMOCRATIC PEOPLES REPUBLIC OF', code: 'KP' },
    { name: 'KOREA REPUBLIC OF', code: 'KR' },
    { name: 'KUWAIT', code: 'KW' },
    { name: 'CAYMAN ISLANDS', code: 'KY' },
    { name: 'KAZAKSTAN', code: 'KZ' },
    { name: 'LAO PEOPLES DEMOCRATIC REPUBLIC', code: 'LA' },
    { name: 'LEBANON', code: 'LB' },
    { name: 'SAINT LUCIA', code: 'LC' },
    { name: 'LIECHTENSTEIN', code: 'LI' },
    { name: 'SRI LANKA', code: 'LK' },
    { name: 'LIBERIA', code: 'LR' },
    { name: 'LESOTHO', code: 'LS' },
    { name: 'LITHUANIA', code: 'LT' },
    { name: 'LUXEMBOURG', code: 'LU' },
    { name: 'LATVIA', code: 'LV' },
    { name: 'LIBYAN ARAB JAMAHIRIYA', code: 'LY' },
    { name: 'MOROCCO', code: 'MA' },
    { name: 'MONACO', code: 'MC' },
    { name: 'MOLDOVA, REPUBLIC OF', code: 'MD' },
    { name: 'MONTENEGRO', code: 'ME' },
    { name: 'SAINT MARTIN', code: 'MF' },
    { name: 'MADAGASCAR', code: 'MG' },
    { name: 'MARSHALL ISLANDS', code: 'MH' },
    { name: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', code: 'MK' },
    { name: 'MALI', code: 'ML' },
    { name: 'MYANMAR', code: 'MM' },
    { name: 'MONGOLIA', code: 'MN' },
    { name: 'MACAU', code: 'MO' },
    { name: 'NORTHERN MARIANA ISLANDS', code: 'MP' },
    { name: 'MAURITANIA', code: 'MR' },
    { name: 'MONTSERRAT', code: 'MS' },
    { name: 'MALTA', code: 'MT' },
    { name: 'MAURITIUS', code: 'MU' },
    { name: 'MALDIVES', code: 'MV' },
    { name: 'MALAWI', code: 'MW' },
    { name: 'MEXICO', code: 'MX' },
    { name: 'MALAYSIA', code: 'MY' },
    { name: 'MOZAMBIQUE', code: 'MZ' },
    { name: 'NAMIBIA', code: 'NA' },
    { name: 'NEW CALEDONIA', code: 'NC' },
    { name: 'NIGER', code: 'NE' },
    { name: 'NIGERIA', code: 'NG' },
    { name: 'NICARAGUA', code: 'NI' },
    { name: 'NETHERLANDS', code: 'NL' },
    { name: 'NORWAY', code: 'NO' },
    { name: 'NEPAL', code: 'NP' },
    { name: 'NAURU', code: 'NR' },
    { name: 'NIUE', code: 'NU' },
    { name: 'NEW ZEALAND', code: 'NZ' },
    { name: 'OMAN', code: 'OM' },
    { name: 'PANAMA', code: 'PA' },
    { name: 'PERU', code: 'PE' },
    { name: 'FRENCH POLYNESIA', code: 'PF' },
    { name: 'PAPUA NEW GUINEA', code: 'PG' },
    { name: 'PHILIPPINES', code: 'PH' },
    { name: 'PAKISTAN', code: 'PK' },
    { name: 'POLAND', code: 'PL' },
    { name: 'SAINT PIERRE AND MIQUELON', code: 'PM' },
    { name: 'PITCAIRN', code: 'PN' },
    { name: 'PUERTO RICO', code: 'PR' },
    { name: 'PORTUGAL', code: 'PT' },
    { name: 'PALAU', code: 'PW' },
    { name: 'PARAGUAY', code: 'PY' },
    { name: 'QATAR', code: 'QA' },
    { name: 'ROMANIA', code: 'RO' },
    { name: 'SERBIA', code: 'RS' },
    { name: 'RUSSIAN FEDERATION', code: 'RU' },
    { name: 'RWANDA', code: 'RW' },
    { name: 'SAUDI ARABIA', code: 'SA' },
    { name: 'SOLOMON ISLANDS', code: 'SB' },
    { name: 'SEYCHELLES', code: 'SC' },
    { name: 'SUDAN', code: 'SD' },
    { name: 'SWEDEN', code: 'SE' },
    { name: 'SINGAPORE', code: 'SG' },
    { name: 'SAINT HELENA', code: 'SH' },
    { name: 'SLOVENIA', code: 'SI' },
    { name: 'SLOVAKIA', code: 'SK' },
    { name: 'SIERRA LEONE', code: 'SL' },
    { name: 'SAN MARINO', code: 'SM' },
    { name: 'SENEGAL', code: 'SN' },
    { name: 'SOMALIA', code: 'SO' },
    { name: 'SURINAME', code: 'SR' },
    { name: 'SAO TOME AND PRINCIPE', code: 'ST' },
    { name: 'EL SALVADOR', code: 'SV' },
    { name: 'SYRIAN ARAB REPUBLIC', code: 'SY' },
    { name: 'SWAZILAND', code: 'SZ' },
    { name: 'TURKS AND CAICOS ISLANDS', code: 'TC' },
    { name: 'CHAD', code: 'TD' },
    { name: 'TOGO', code: 'TG' },
    { name: 'THAILAND', code: 'TH' },
    { name: 'TAJIKISTAN', code: 'TJ' },
    { name: 'TOKELAU', code: 'TK' },
    { name: 'TIMOR-LESTE', code: 'TL' },
    { name: 'TURKMENISTAN', code: 'TM' },
    { name: 'TUNISIA', code: 'TN' },
    { name: 'TONGA', code: 'TO' },
    { name: 'TURKEY', code: 'TR' },
    { name: 'TRINIDAD AND TOBAGO', code: 'TT' },
    { name: 'TUVALU', code: 'TV' },
    { name: 'TAIWAN, PROVINCE OF CHINA', code: 'TW' },
    { name: 'TANZANIA, UNITED REPUBLIC OF', code: 'TZ' },
    { name: 'UKRAINE', code: 'UA' },
    { name: 'UGANDA', code: 'UG' },
    { name: 'UNITED STATES', code: 'US' },
    { name: 'URUGUAY', code: 'UY' },
    { name: 'UZBEKISTAN', code: 'UZ' },
    { name: 'HOLY SEE (VATICAN CITY STATE)', code: 'VA' },
    { name: 'SAINT VINCENT AND THE GRENADINES', code: 'VC' },
    { name: 'VENEZUELA', code: 'VE' },
    { name: 'VIRGIN ISLANDS, BRITISH', code: 'VG' },
    { name: 'VIRGIN ISLANDS, U.S.', code: 'VI' },
    { name: 'VIET NAM', code: 'VN' },
    { name: 'VANUATU', code: 'VU' },
    { name: 'WALLIS AND FUTUNA', code: 'WF' },
    { name: 'SAMOA', code: 'WS' },
    { name: 'KOSOVO', code: 'XK' },
    { name: 'YEMEN', code: 'YE' },
    { name: 'MAYOTTE', code: 'YT' },
    { name: 'SOUTH AFRICA', code: 'ZA' },
    { name: 'ZAMBIA', code: 'ZM' },
    { name: 'ZIMBABWE', code: 'ZW' },]
